# NUMPY ASSIGNMENT

#### 1. Import the numpy package under the name np 

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration

In [3]:
np.__version__

'1.26.3'

#### 3. Create a null vector of size 10 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array 

In [5]:
arr = np.array([[2,2,3,4], [7,8,9]])
memorysize = arr.size
print(memorysize)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

#### 5.How to get the documentation of the numpy add function from the command line? 

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
Null_Vector = np.zeros(10)
Null_Vector[4] = 1
print(Null_Vector)


NameError: name 'np' is not defined

#### 7. Create a vector with values ranging from 10 to 49 

In [ ]:
Value_Range = np.arange(10,50)
Value_Range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) 

In [ ]:
Value_Range = np.arange(10,50)
reverse = Value_Range[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matr = np.arange(9).reshape(3, 3)
print(matr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

#### 11. Create a 3x3 identity matrix


In [ ]:
identity= np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
identity

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

#### 12. Create a 3x3x3 array with random values

In [ ]:
random_var = np.random.randint(20,299 , size=(3, 3, 3))
random_var

array([[[233, 147, 101],
        [ 87, 295, 210],
        [ 29, 123, 209]],

       [[ 66,  66, 194],
        [216, 230, 198],
        [232,  39, 135]],

       [[260,  52,  52],
        [ 73, 234, 219],
        [282, 186, 261]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values 

In [ ]:
rand = np.random.randint(1, 999 ,size=(10, 10))
rand
print('minimum value is ', rand.min())
print('maximum value is ', rand.max())

minimum value is  2
maximum value is  993


#### 14. Create a random vector of size 30 and find the mean value 

In [ ]:
randVec = np.random.randint(34,890, size=30)
print(randVec)
print('mean value is ', randVec.mean())

[860 744 154 715 126 100 644 494 162 312 152 267 759 570 124 420 167 130
 260 501 610 106 855 868 757 750 113 383 717 418]
mean value is  441.26666666666665


#### 15. Create a 2d array with 1 on the border and 0 inside 

In [ ]:
border = np.ones((7, 7))
print("Arary:")
print(border)
border[1:-1, 1:-1] = 0
print(border)

Arary:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:

border = np.pad(border, pad_width=1, mode='constant', constant_values=0)
print(border)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
diagonal= np.diag([1, 2, 3, 4])
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
checker = np.zeros((8,8),dtype=int)
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print(checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
shape = (6, 7, 8)
index_1d = 100

index_3d = np.unravel_index(index_1d, shape)

print("Index (x, y, z) of the 100th element:", index_3d)


Index (x, y, z) of the 100th element: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
checkerboard8x8 =np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

print(checkerboard8x8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [ ]:
normal = np.random.random((5,5))
normal_mat = (normal - np.mean (normal)) / (np.std (normal))
print(normal_mat)

[[-1.25882963e+00 -1.05706042e-01  5.82506801e-01  1.48266596e+00
  -1.60282688e+00]
 [ 1.51101343e+00  4.06261781e-01 -1.65496782e+00  1.68539729e+00
  -7.50939027e-02]
 [ 7.33961290e-04 -1.92077463e-01  1.73780263e+00 -9.76461150e-01
   1.99104274e-01]
 [ 1.53016219e+00  4.60753279e-02 -4.16997197e-01 -1.74379730e-02
  -7.52683119e-01]
 [-6.96259945e-02  7.09816063e-01 -7.79663274e-01 -8.62289031e-01
  -1.12688023e+00]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [ ]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])


color_array = np.array([(255, 0, 0, 255),  
                        (0, 255, 0, 255),  
                        (0, 0, 255, 128)],  
                       dtype=color_dtype)


print(color_array)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 128)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [ ]:
five_by_three_mat = np.random.random ((5, 3))

Three_by_two= np.random.random ((3, 2))


real_mat= np.dot(five_by_three_mat, Three_by_two)
real_mat

array([[1.74955132, 0.81022681],
       [1.04933689, 0.45319731],
       [1.14878701, 0.50121519],
       [0.81704239, 0.41043107],
       [0.94168192, 0.39608272]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [ ]:
one_d = np.arange(10)
one_d[(3 < one_d) & (one_d < 8)] *= -1
one_d

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? 
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
Z= np.arange(10)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\pc\AppData\Local\Temp\ipykernel_11200\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\pc\AppData\Local\Temp\ipykernel_11200\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\pc\AppData\Local\Temp\ipykernel_11200\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ?

In [ ]:
Zero = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

print(np.where(Zero>0, np.ceil(Zero), np.floor(Zero)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ -2.  10.   8.   1. -10.   7.   7. -10.  -6.  -1.]


#### 30. How to find common values between two arrays?

In [ ]:
val1 = np.arange(23)
val2= np.arange(17,34)
print(np.intersect1d(val1,val2))

[17 18 19 20 21 22]


#### 31. How to ignore all numpy warnings (not recommended)?

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\pc\AppData\Local\Temp\ipykernel_6100\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [ ]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64("today") 
tomorrow = np.datetime64("today") - np.timedelta64(1)
print("Yesterday was ",yesterday)
print("Todays date is ",today)
print('Tomorrow will be ',tomorrow)

Yesterday was  2024-02-10
Todays date is  2024-02-11
Tomorrow will be  2024-02-10


#### 34. How to get all the dates corresponding to the month of July 2016? 

In [ ]:
import calendar
year = 2016
month = 7

first_day, last_day = calendar.monthrange(year, month)

dates_array = np.array([np.datetime64(f"{year}-{month:02d}-{day:02d}") for day in range(1, last_day + 1)])


print(dates_array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C= ((A + B) *  (-A / 2) )
  

print(C)


[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
num = np.random.randint(34, 1234, 10)
print(num - num%1)
print(num // 1)
print(np.floor(num))
print(num.astype(int))
print(np.trunc(num))

[ 790 1021 1020  633 1116  625  951  721 1058  974]
[ 790 1021 1020  633 1116  625  951  721 1058  974]
[ 790. 1021. 1020.  633. 1116.  625.  951.  721. 1058.  974.]
[ 790 1021 1020  633 1116  625  951  721 1058  974]
[ 790. 1021. 1020.  633. 1116.  625.  951.  721. 1058.  974.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [ ]:
arrr = np.ones((5,5))
arr = np.arange(5) * arrr
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array 

In [1]:
def generator():
    for i in range(10):
        yield i
arr = np.fromiter(generator(),dtype=int64,count=-1)
print(arr)

NameError: name 'np' is not defined

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [12]:
Vect = np.linspace(0,1, 12 ,endpoint=True)[1: -1]
print(Vect)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [9]:
RandVect = np.random.randint(3, 89, size = 10)
RandVect.sort()
print(RandVect)

[ 7 14 17 27 48 67 68 70 85 88]


#### 41. How to sum a small array faster than np.sum? 

In [13]:
np.add.reduce(RandVect)

491

#### 42. Consider two random array A and B, check if they are equal

In [22]:
a = np.random.randint(76,199,5)
b = np.random.randint(88,190,5)
print(a)
print(b)
equal = np.allclose(a,b)
print(equal)


[117 179 107 155  82]
[186 102 157 149 114]
False


#### 43. Make an array immutable (read-only)

In [23]:
arra = np.arange(56,990, 6)
arra.flags.writeable = False
arra[23]=8

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [28]:
c = np.random.randint(23,567 , (10,2))
c
a,b = c[:,0], c[:,1]
e = np.sqrt(a**2+b**2)
f = np.arctan2(b,a)
print(e)
print(f)


[601.22707857 500.95309162 606.84512027 322.27317605 291.63161694
 679.400471   511.13207686 257.20031104 103.84603989 454.71419595]
[0.50903711 1.23515778 0.65569563 0.50529019 0.40534203 0.6423236
 0.42338916 0.6419459  1.29778762 0.77140219]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [29]:
VecMax = np.random.randint(34,78,10)
VecMax[VecMax.argmax()] = 0
print(VecMax)

[38 69 47 66 38 40 54 48  0 66]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [ ]:
s = np.zeros((5,5), [('x',float),('y',float)])
s['x'], s['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(s)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 

In [31]:
x = np.random.randint(34,78, 9)
y = np.random.randint(45,100, 9)
Cauchy = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(Cauchy))

1.5254899813847763e-39


#### 48. Print the minimum and maximum representable value for each numpy scalar type

#### 49. How to print all the values of an array? 

In [43]:

Arr = np.random.randint(20, 200, size = (18, 17))
np.set_printoptions(threshold=np.inf)
print(Arr)

[[ 62  30  76 121 192  87  25  84  71  54  76  44 103 160  64 136 155]
 [187 175 114  65 102 135 154  75 151 165 196 176  81 144  39  61  92]
 [ 54 116  73 100 145  79 166 161  37  49 147 115 140  47 121  80  79]
 [ 69 164  42 191 104  29  71 102 172 140 183 115 153 138 168  89  74]
 [ 31 199 141 133  73  98 172 103 153 170 121  76  76 146  43 121  75]
 [154  50  33 176 177  36  47 136 137 165 197 149 126 162 199 109 193]
 [ 73  69 116  75  65 179 159 196  86 101  26  86  50 147 127  38 143]
 [ 82 187 100  48 154 193 133 189 135 180 138 179 196  53 162  30 168]
 [195  56  84  94 160  91 171  97  58 199 180 162 191 162  45 147 134]
 [183  41 131 172 146 116  37 189 121 199  87 100 189 114 179 134  67]
 [ 37  26  66 140 117  85 175  41 139  89 161  21  76  93 135 139  29]
 [128 175  90  53 156 197  87 152 143 196 120 145  90 167  99 102  25]
 [ 25  57 109 192 147 132  85  43  78 176  58 160  26 162  47  23 185]
 [ 97  99 153 147 141 135  83 107 195  46 158  36  69  77  34 102 137]
 [183 

#### 50. How to find the closest value (to a given scalar) in a vector? 

In [47]:
vec= np.arange(25)


sca = 5

index = np.abs(vec - sca).argmin()

clo_val = vec[index]

print(clo_val)

5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [49]:

pos_dtype= [('x', int), ('y', int)]
color_dtype = [('r', int), ('g', int), ('b', int)]


positions = np.array([(33, 3), (44, 5)], dtype=pos_dtype)
colors = np.array([(255, 0, 0), (0, 255, 0)], dtype=color_dtype)

# Combine position and color arrays
arra = np.empty(2, dtype=[('position', pos_dtype), ('color', color_dtype)])
arra['position'] = positions
arra['color'] = colors

print(arra)



[((33, 3), (255,   0, 0)) ((44, 5), (  0, 255, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [50]:
arr = np.random.randint(34, 789, size=(100,2))
piont_dist = np.sqrt(np.sum((arr - arr[:, np.newaxis])**2, axis=-1))

print(piont_dist)

[[  0.         400.58582102 833.60002399 630.27057682 692.31495723
  643.18348859 306.21724315 643.20525495 445.17973898 821.65199446
  519.06165337 429.78366651 563.89006021 340.53046853 111.30588484
  536.85938569 556.00809347 569.12915933 475.79827658 651.09292732
  701.07702858 210.26174165 189.23530326 634.56520548 631.31133365
  104.21612159 401.29914029  96.33794683 570.46735226 494.87473162
  301.24574686 198.56736892 213.19005605 422.85931467  79.07591289
  583.33180952 748.505177   635.70826642 713.58531375  47.92702787
  645.97523172 398.67028984 610.00327868 617.68762332 632.60256085
  266.12027356 570.85287071 336.78628238 325.3567273  387.07234466
  715.28735484 322.39882134 367.44115175 254.57808232 632.92495606
  469.11405863 247.73574631 448.1350243  498.83163492 540.82899331
  270.68062361 463.23752007 551.42089188 448.00111607 132.96992141
  177.04519197 842.91162052 588.80387227 815.61265316 125.35549449
  141.48498154 602.53630596 456.07017004 334.34862045 480.1301

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [57]:
float_array = np.array([5.67, 89.49, 4.8], dtype=np.float32)

float_array.view(dtype=np.int32)[:] = float_array

print(float_array)

[7.01e-45 1.25e-43 5.61e-45]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [58]:

data = np.genfromtxt('fifty_four.txt', delimiter=',', dtype=float, missing_values='')


print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? 

In [65]:
arr = np.random.randint(23, 98, 23)
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 43
(1,) 45
(2,) 80
(3,) 69
(4,) 48
(5,) 28
(6,) 83
(7,) 71
(8,) 73
(9,) 36
(10,) 68
(11,) 95
(12,) 56
(13,) 52
(14,) 55
(15,) 50
(16,) 86
(17,) 50
(18,) 61
(19,) 47
(20,) 27
(21,) 32
(22,) 41


#### 56. Generate a generic 2D Gaussian-like array 

#### 57. How to randomly place p elements in a 2D array?

In [66]:
n = 10
p = 3
z = np.random((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),1)
print(z)

TypeError: 'module' object is not callable

#### 58. Subtract the mean of each row of a matrix 

#### 59. How to sort an array by the nth column? 

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array 

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

#### 63. Create an array class that has a name attribute

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? 

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product? 

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

#### 72. How to swap two rows of an array? 

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

#### 75. How to compute averages using a sliding window over an array? 

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) 

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

#### 82. Compute a matrix rank

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods 

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows? 

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [52]:
a = np.array([[2.5, -7.5, 8], [0, -2, 4.5]])
print(a)

[[ 2.5 -7.5  8. ]
 [ 0.  -2.   4.5]]
